# Generated by Django 5.1.3 on 2025-10-05 12:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('facilities', models.TextField(blank=True)),
                ('ticket_price_weekday', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ticket_price_weekend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parking_motor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parking_car', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.URLField(blank=True)),
                ('coordinates', models.CharField(blank=True, max_length=100)),
                ('opening_hours', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rekomendasi.category')),
            ],
        ),
    ]
