# Generated by Django 5.1.3 on 2025-11-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0002_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='parking_car',
        ),
        migrations.RemoveField(
            model_name='place',
            name='parking_motor',
        ),
        migrations.RemoveField(
            model_name='place',
            name='ticket_price_weekday',
        ),
        migrations.RemoveField(
            model_name='place',
            name='ticket_price_weekend',
        ),
        migrations.AddField(
            model_name='place',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='ticket_info',
            field=models.TextField(blank=True, help_text='Contoh: Weekday 10k, Weekend 20k, Parkir motor 2k, mobil 5k'),
        ),
    ]
